name: Revive
version: '${version}'
api-version: '1.21'
author: Donut
main: us.donut.revive.Main
softdepend: [JumanjiAtlas]
commands:
  reloadrevive:
    description: Reload Revive configuration.
    permission: revive.reload
  revivepotion:
    description: Give a splash revive potion.
    usage: /revivepotion [player] [amount]
    permission: revive.potion.give
permissions:
  revive.disable:
    description: Prevents a player from being revived
    default: false
  revive.reload:
    description: Allows /reloadrevive
    default: op
  revive.potion.give:
    description: Gives splash revive potions.
    default: op
